server:
  port: 8085
spring:
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yx_tpl?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&socketTimeout=60000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
  # MinIO连接信息
minio:
  access-key: HhoPRE75GRPYytJkw0tK
  secret-key: uqX7Dy4qPQgLLsiPj6GfT0nqqdTxyKurckLgwx9g
  endpoint:  http://127.0.0.1:9000
  bucket: minioserverfile
  size: 1
  # 禁止上传的文件
  not-support-file-type: js,html,htm,shtml,php,css,java,sh,bat,xml

kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1